"""
Small Einstein-field-equation tensor sandbox for the game.

This is intentionally not a full numerical-relativity solver.  It does the
piece that the current Three.js game does not do: given a metric g_mu_nu, it
computes Christoffel symbols, the Ricci tensor, the Ricci scalar, the Einstein
tensor, and the effective stress-energy tensor from

    G_mu_nu + Lambda g_mu_nu = 8 pi T_mu_nu

The metric is a weak-field 4D spacetime metric whose potential is generated by
game-like mass wells in the x/y plane:

    ds^2 = -(1 + 2 Phi) dt^2 + (1 - 2 Phi)(dx^2 + dy^2 + dz^2)

The game can use Phi as the curved-surface height proxy and -grad(Phi) as the
slow-speed geodesic acceleration intuition.
"""

from functools import lru_cache
from math import isfinite, pi, sqrt


DIM = 4
COORD_NAMES = ("t", "x", "y", "z")

FINITE_DIFF_H = 1.0e-3
SYMMETRY_TOL = 1.0e-6
SOFTENING = 0.35
PHI_SCALE = 0.01
Z_SCALE = 0.98
LAMBDA = 0.0

# A level-3-like layout copied from the JavaScript game shape.
MASSES = (
    {"x": -2.0, "y": 0.8, "mass": 4.2},
    {"x": 0.6, "y": -0.4, "mass": 7.8},
    {"x": 2.6, "y": 2.1, "mass": 2.8},
)


def shifted(point, axis, delta):
    values = list(point)
    values[axis] += delta
    return tuple(values)


@lru_cache(maxsize=None)
def phi(point):
    """Weak-field gravitational potential Phi(x, y)."""
    x = point[1]
    y = point[2]
    total = 0.0
    for source in MASSES:
        dx = x - source["x"]
        dy = y - source["y"]
        r = sqrt(dx * dx + dy * dy + SOFTENING * SOFTENING)
        total -= PHI_SCALE * source["mass"] / r
    return total


def height_proxy(point):
    """Same visual idea as main.js heightAt: height is proportional to Phi."""
    return (Z_SCALE / PHI_SCALE) * phi(point)


def metric_component(point, mu, nu):
    """Diagonal weak-field metric g_mu_nu with signature (-, +, +, +)."""
    if mu != nu:
        return 0.0

    potential = phi(point)
    if mu == 0:
        return -(1.0 + 2.0 * potential)
    return 1.0 - 2.0 * potential


def inverse_metric_component(point, mu, nu):
    if mu != nu:
        return 0.0
    return 1.0 / metric_component(point, mu, mu)


def partial_metric(point, axis, mu, nu):
    """Partial derivative d_axis g_mu_nu by central finite difference."""
    if axis in (0, 3) or mu != nu:
        return 0.0

    plus = shifted(point, axis, FINITE_DIFF_H)
    minus = shifted(point, axis, -FINITE_DIFF_H)
    return (metric_component(plus, mu, nu) - metric_component(minus, mu, nu)) / (2.0 * FINITE_DIFF_H)


@lru_cache(maxsize=None)
def gamma(point, rho, mu, nu):
    """Christoffel symbol Gamma^rho_{mu nu}."""
    total = 0.0
    for sigma in range(DIM):
        inv = inverse_metric_component(point, rho, sigma)
        if inv == 0.0:
            continue
        total += inv * (
            partial_metric(point, mu, sigma, nu)
            + partial_metric(point, nu, sigma, mu)
            - partial_metric(point, sigma, mu, nu)
        )
    return 0.5 * total


def partial_gamma(point, axis, rho, mu, nu):
    """Partial derivative d_axis Gamma^rho_{mu nu}."""
    if axis in (0, 3):
        return 0.0

    plus = shifted(point, axis, FINITE_DIFF_H)
    minus = shifted(point, axis, -FINITE_DIFF_H)
    return (gamma(plus, rho, mu, nu) - gamma(minus, rho, mu, nu)) / (2.0 * FINITE_DIFF_H)


def ricci_tensor(point):
    """Ricci tensor R_mu_nu from Christoffel symbols."""
    tensor = [[0.0 for _ in range(DIM)] for _ in range(DIM)]

    for mu in range(DIM):
        for nu in range(DIM):
            derivative_terms = 0.0
            for rho in range(DIM):
                derivative_terms += partial_gamma(point, rho, rho, mu, nu)
                derivative_terms -= partial_gamma(point, nu, rho, mu, rho)

            quadratic_terms = 0.0
            for rho in range(DIM):
                for sigma in range(DIM):
                    quadratic_terms += gamma(point, rho, mu, nu) * gamma(point, sigma, rho, sigma)
                    quadratic_terms -= gamma(point, sigma, mu, rho) * gamma(point, rho, nu, sigma)

            tensor[mu][nu] = derivative_terms + quadratic_terms

    return tensor


def ricci_scalar(point, ricci):
    scalar = 0.0
    for mu in range(DIM):
        for nu in range(DIM):
            scalar += inverse_metric_component(point, mu, nu) * ricci[mu][nu]
    return scalar


def einstein_tensor(point):
    """Einstein tensor G_mu_nu = R_mu_nu - 1/2 R g_mu_nu."""
    ricci = ricci_tensor(point)
    scalar = ricci_scalar(point, ricci)
    tensor = [[0.0 for _ in range(DIM)] for _ in range(DIM)]

    for mu in range(DIM):
        for nu in range(DIM):
            tensor[mu][nu] = ricci[mu][nu] - 0.5 * scalar * metric_component(point, mu, nu)

    return tensor, ricci, scalar


def effective_stress_energy(point, einstein):
    """T_mu_nu implied by the chosen metric through the EFE."""
    tensor = [[0.0 for _ in range(DIM)] for _ in range(DIM)]
    for mu in range(DIM):
        for nu in range(DIM):
            left_side = einstein[mu][nu] + LAMBDA * metric_component(point, mu, nu)
            tensor[mu][nu] = left_side / (8.0 * pi)
    return tensor


def grad_phi(point):
    d_phi = []
    for axis in (1, 2):
        plus = shifted(point, axis, FINITE_DIFF_H)
        minus = shifted(point, axis, -FINITE_DIFF_H)
        d_phi.append((phi(plus) - phi(minus)) / (2.0 * FINITE_DIFF_H))
    return tuple(d_phi)


def slow_geodesic_accel(point):
    """
    Slow-particle coordinate acceleration.

    For this weak-field metric, d2 x^i / dt^2 ~= -Gamma^i_{00}, which is the
    relativistic route to the game-like acceleration a ~= -grad(Phi).
    """
    return (-gamma(point, 1, 0, 0), -gamma(point, 2, 0, 0))


def max_efe_residual(point, einstein, stress_energy):
    max_abs = 0.0
    for mu in range(DIM):
        for nu in range(DIM):
            left_side = einstein[mu][nu] + LAMBDA * metric_component(point, mu, nu)
            right_side = 8.0 * pi * stress_energy[mu][nu]
            max_abs = max(max_abs, abs(left_side - right_side))
    return max_abs


def format_matrix(matrix):
    rows = []
    for row in matrix:
        rows.append("[" + ", ".join(f"{value: .6e}" for value in row) + "]")
    return "\n".join(rows)


def run_smoke_tests(samples):
    for label, point in samples:
        g00 = metric_component(point, 0, 0)
        g11 = metric_component(point, 1, 1)
        assert g00 < 0.0, f"{label}: metric lost time-like sign"
        assert g11 > 0.0, f"{label}: metric lost space-like sign"

        einstein, ricci, scalar = einstein_tensor(point)
        stress_energy = effective_stress_energy(point, einstein)
        residual = max_efe_residual(point, einstein, stress_energy)
        assert residual < 1.0e-12, f"{label}: EFE residual too large: {residual}"
        assert isfinite(scalar), f"{label}: non-finite Ricci scalar"

        for mu in range(DIM):
            for nu in range(DIM):
                assert isfinite(ricci[mu][nu]), f"{label}: non-finite Ricci tensor"
                assert isfinite(einstein[mu][nu]), f"{label}: non-finite Einstein tensor"
                assert abs(einstein[mu][nu] - einstein[nu][mu]) < SYMMETRY_TOL, f"{label}: G is not symmetric"


def main():
    samples = (
        ("launch-ish point", (0.0, -5.9, -2.9, 0.0)),
        ("near central well", (0.0, 0.1, -0.1, 0.0)),
        ("target-ish point", (0.0, 6.1, -2.7, 0.0)),
    )

    run_smoke_tests(samples)

    for label, point in samples:
        einstein, ricci, scalar = einstein_tensor(point)
        stress_energy = effective_stress_energy(point, einstein)
        dphidx, dphidy = grad_phi(point)
        ax, ay = slow_geodesic_accel(point)

        print(f"\n=== {label} at x={point[1]:.2f}, y={point[2]:.2f} ===")
        print(f"Phi:                 {phi(point): .6e}")
        print(f"height proxy:        {height_proxy(point): .6e}")
        print(f"Ricci scalar R:      {scalar: .6e}")
        print(f"effective T_00:      {stress_energy[0][0]: .6e}")
        print(f"-grad(Phi):          ({-dphidx: .6e}, {-dphidy: .6e})")
        print(f"-Gamma^i_00 accel:   ({ax: .6e}, {ay: .6e})")
        print("Einstein tensor G_mu_nu:")
        print(format_matrix(einstein))

    print("\nSmoke tests passed.")


if __name__ == "__main__":
    main()
